---
# tasks file for win_ad_install
- name: Install AD-Domain-Service
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name: Create new forest
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: result

- name: Reboot after creation
  win_reboot:
    msg: "Server config in progress; rebooting..."
  when: result.reboot_required


- name: List available domain
  win_command: nltest /dclist:"{{ ad_domain_name }}"
  register: domain_list

- debug:
    var: domain_list



