---
# tasks file for win_domain_user
- name: Create AD User
  win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    state: present
    email: '"{{ item.name }}@ad.{{ GUID }}".example.opentlc.com'
  with_items: "{{ user_info }}"
