---
# tasks file for win_service_config

- name: Install  packages on windows 
  win_chocolatey:
    name: '{{ item }}'
    params: "{{ parameters }}"
    state: present
  with_items: '{{ package_name }}'
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'
  tags: install_packages

- name: Start the window services
  win_service:
    name: "{{ item }}"
    start_mode: auto
    state: started
  with_items: '{{ service_name }}'
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'
  tags: start_services

- name: Add win_firewall_rule
  win_firewall_rule:
     name: "{{ service_name }}"
     localport: "{{ local_port }}"
     action: allow
     direction: in
     protocol: "{{ protocol_name }}"
     state: present
     enabled: yes
  tags: firewall_rule

